language: node_js
node_js: stable

before_deploy:
  - npm install

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN} # Set in travis-ci.org dashboard
  local_dir: public
  target_branch: master
  repo: $GH_REF
  on:
    branch: picidae

env:
 global:
   - GH_REF: https://github.com/imcuttle/imcuttle.github.io.git