language: node_js
node_js: 8
cache:
  bundler: true
  directories:
    - node_modules

install:
  - npm install
script:
  - npm run build
deploy:
  # edge:
    # branch: v1.8.47
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN} # Set in travis-ci.org dashboard
  local_dir: public
  target_branch: master
  repo: $GH_REF
  on:
    branch: picidae

env:
  global:
    - GH_REF: imcuttle/imcuttle.github.io